version: '3'

volumes:
  db_data:

services:
  nginx:
    image: auth-api:lb  
    ports:
      - "80:80"
    environment:
      - HOSTNAME=auth-api, *.auth-api
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/auth_api.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - auth-api
  db:
    image: auth-api:db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=lewy
      - POSTGRES_PASSWORD=aaa
  auth-api:
    image: auth-api:app
    volumes:
      - /home/demonizer/projects/rest/auth-api/auth_api:/root/auth-api/auth_api
    environment:
      - DB_USER=lewy
      - DB_PASSWORD=aaa
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=auth_api.settings